# fly.toml app configuration file generated for whatsappbot-holy-grass-1 on 2024-12-08T17:53:14+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whatsappbot-holy-grass-1'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
