services:
  - type: web
    name: whatsapp-bot
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    installCommand: |
      apt-get update && apt-get install -y \
      libatk1.0-0 \
      libatk-bridge2.0-0 \
      libcups2 \
      libxcomposite1 \
      libxrandr2 \
      libxdamage1 \
      libxshmfence1 \
      libgbm-dev